let language =
[
	{//-------简体中文
		// 家族管理————》主播页面
		language1:"家族管理",
		language2:"（最多可加入1个家族）",
		language3:"空空如也，快去寻找组织",
		language4:"申请加入中",
		language5:"已通过审核",
		language6:"未通过审核",
		language7:"加入家族",
		language8:"请输入家族ID",
		language9:"确定",
		language10:"主播",
		language11:"场控",
		language12:"同意",
		language13:"拒绝",
		language14:"移除",
		language15:"添加场控",
		language16:"请输入ID",
		language17:"申请成功",
		language18:"已存在家族",
		language19:"该家族不存在",
		language20:"请勿重复提交",
		language21:"失败",
		language22:"成功",
		language23:"已存在家族,移除申请记录",
		language24:"操作失败",
		language25:"该ID已是场控",
		language26:"当前ID不是本家族",
		language27:"场控最多4个！",
		language28:"收益管理",
		language29:"宝宝",
		language30:"流水",
		language31:"时长",
		language32:"本周",
		language33:"上周",
		language34:"日期",
		language35:"数量",
		language36:"总计",
		language36:"粉丝亲密榜",
		language37:"排行",
		language38:"用户排行&亲密值",
		language39:"勋章&等级",
		language40:"暂无数据",
		language41:"赠送礼物 加入粉丝团",
		language42:"专属粉丝团勋章",
		language43:"尊贵观众席位",
		language44:"粉丝亲密榜",
		language45:"粉丝榜",
		

		
		
		
	 
	 
	},
	{//-------繁體中文
		// 家族管理————》主播頁面
		language1:"家族管理",
		language2:"（最多可加入1個家族）",
		language3:"空空如也，快去尋找組織",
		language4:"申請加入中",
		language5:"已通過審核",
		language6:"未通過審核",
		language7:"加入家族",
		language8:"請輸入家族ID",
		language9:"確定",
		language10:"主播",
		language11:"場控",
		language12:"同意",
		language13:"拒絕",
		language14:"移除",
		language15:"添加場控",
		language16:"請輸入ID",
		language17:"申請成功",
		language18:"已存在家族",
		language19:"該家族不存在",
		language20:"請勿重復提交",
		language21:"失敗",
		language22:"成功",
		language23:"已存在家族,移除申請記錄",
		language24:"操作失敗",
		language25:"該ID已是場控",
		language26:"當前ID不是本家族",
		language27:"場控最多4個！",
		language28:"收益管理",
		language29:"寶寶",
		language30:"流水",
		language31:"時長",
		language32:"本周",
		language33:"上周",
		language34:"日期",
		language35:"數量",
		language36:"總計",
		language36:"粉絲親密榜",
		language37:"排行",
		language38:"用戶排行&親密值",
		language39:"勛章&等級",
		language40:"暫無數據",
		language41:"贈送禮物 加入粉絲團",
		language42:"專屬粉絲團勛章",
		language43:"尊貴觀眾席位",
		language44:"粉絲親密榜",
		language45:"粉絲榜",

	},
	{//-------英文
		// Family Management————》Host page
		language1:"Family Management",
		language2:"（Max ONE Family）",
		language3:"No family, find a family now",
		language4:"Applying",
		language5:"Verified",
		language6:"Not verified",
		language7:"Join family",
		language8:"Enter family ID",
		language9:"Confirm",
		language10:"Host",
		language11:"Admin",
		language12:"Agree",
		language13:"Reject",
		language14:"Remove",
		language15:"Add admin",
		language16:"Enter ID",
		language17:"Applied",
		language18:"Existing family",
		language19:"Family not exist",
		language20:"Do not repeat submission",
		language21:"Fail",
		language22:"Success",
		language23:"Family existed, please remove application",
		language24:"Fail",
		language25:"This ID is already an admin",
		language26:"Current ID is not in the family",
		language27:"Max 4 admins only！",
		language28:"Revenue Manager",
		language29:"Baby",
		language30:"Flow",
		language31:"Duration",
		language32:"This week",
		language33:"Last week",
		language34:"Date",
		language35:"Amount",
		language36:"Total",
		language36:"Fans loyalty list",
		language37:"Ranking",
		language38:"Users’ ranking and loyalty point",
		language39:"Medal & Level",
		language40:"No data",
		language41:"Send gift to join fans group",
		language42:"Exclusive fans medal",
		language43:"Noble audience seating",
		language44:"Fans loyalty ranking",
		language45:"Loyalty ranking",

	},	
	{//-------马来语
		// Pengurusan keluarga————》Halaman hos
		language1:"Pengurusan keluarga",
		language2:"（Paling banyak 1 keluarga sahaja）",
		language3:"Kosong, mari sertai kumpulan",
		language4:"Sedang memohon",
		language5:"Diluluskan",
		language6:"Belum dilulus",
		language7:"Sertai keluarga",
		language8:"Masukkan ID keluarga",
		language9:"Pasti",
		language10:"Hos",
		language11:"Admin",
		language12:"Setuju",
		language13:"Tolak",
		language14:"Keluarkan",
		language15:"Tambah admin",
		language16:"Masukkan ID",
		language17:"Permohonan berjaya",
		language18:"Keluarga wujud",
		language19:"Keluarga tidak wujud",
		language20:"Jangan berulang hantar",
		language21:"Gagal",
		language22:"Berjaya",
		language23:"Keluarga wujud, keluarkan permohonan",
		language24:"Gagal",
		language25:"ID ini adalah admin",
		language26:"ID ini bukan keluarga ini",
		language27:"Paling banyak 4 admin！",
		language28:"Pengurusan hasil",
		language29:"Sayang",
		language30:"Aliran",
		language31:"Tempoh",
		language32:"Minggu ini",
		language33:"Minggu lepas",
		language34:"Tarikh",
		language35:"Amaun",
		language36:"Jumlah",
		language36:" Senarai Keintiman Peminat ",
		language37:"Senarai",
		language38:"Senarai & Nilai keintiman peminat",
		language39:"Pingat & level",
		language40:"Tiada data",
		language41:"Hantar hadiah untuk masuk kumpulan peminat",
		language42:"Pingat peminat ekslusif",
		language43:"Tempat penonton terhormat",
		language44:"Senarai Keintiman Peminat ",
		language45:"Senarai peminat",
	}
]

export default
{
  language,//tag数组 test
}